---
title: "lobster"
author: "Yingfei Jiang"
date: "11/12/2018"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}

library(tidyverse)
library(vcdExtra)
library(ggpubr)
library(car)
library(onewaytests)
library(kableExtra)
library(effsize)
#Loading packages

lob_a_draft <- read_csv("lobster_size_abundance.csv")
lob_t_draft <- read_csv("lobster_traps.csv")

```


```{r, include = FALSE}

#Some basic data wrangling in this chunk, column lob_year is for future use when plotting trend, here i am assuming fishing season "x-x+1" is counted as year x+1. This means when we analyze trap count in the future, it is the trap count before the lobster count of the same year, which is collected in August  

lob_a_draft <- as.data.frame(lob_a_draft) #coerce to data.frame
lob_a <- expand.dft(lob_a_draft, freq = "COUNT") #get the data into case format


lob_t <- lob_t_draft %>% 
  mutate(
    lob_year = case_when(
      FISHING_SEASON == "2012-2013" ~ 2013,
      FISHING_SEASON == "2013-2014" ~ 2014,
      FISHING_SEASON == "2014-2015" ~ 2015,
      FISHING_SEASON == "2015-2016" ~ 2016,
      FISHING_SEASON == "2016-2017" ~ 2017
    )
  )

```

### 1. Lobster Abundance and Fishing Pressure 2012-2017
```{r, message=FALSE, echo = FALSE, warning = FALSE}

#Plotting trend in lobster count and trap count

#lob_a_trend stores lobster counts based on year and site
lob_a_trend <- lob_a %>%
  group_by(YEAR, SITE) %>%
  summarize(lob_counts = length(SIZE))

#lob_t_trend stores total observed trap counts through the fishing season by year and location, this doesnt necessarily make sense since observations are made on selected days.
lob_t_trend <- lob_t %>%
  filter (
    SITE == "AQUE" |
    SITE == "NAPL" |
    SITE == "MOHK" |
    SITE == "IVEE" |
    SITE == "CARP"
    ) %>% 
  group_by(lob_year, SITE) %>% 
  summarize(trap_counts = sum(TRAPS)) %>% 
  #summarize(trap_counts = round(mean(TRAPS), 2)) %>% 
  rename(YEAR = lob_year)

trend <- full_join(lob_a_trend, lob_t_trend)

trend_plot <- ggplot(trend) +
  geom_line(aes(x = YEAR, y = lob_counts, color = "Lobster Counts")) +
  geom_line(aes(x = YEAR - 0.5, y = trap_counts, color = "Trap Counts")) +
  scale_y_continuous(sec.axis = sec_axis(~., name = "Trap Counts")) +
  facet_wrap(~SITE, scale = "free") +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10)) +
  labs(x = "Year",
       y = "Lobster Counts",
       colour = "Counts")
  

trend_plot

```

### 2. Compare Mean Lobster Size by Site in 2017

```{r, message=FALSE, echo = FALSE}


# Visualization for lobster size at five sites, we need to decide which plot is better

#Visualization for lobster size at five sites, we need to decide which plot is better
#The second one!

lob_a_2017 <- lob_a %>%
  filter(YEAR == 2017)

lob_a_2017_box <- ggplot(lob_a_2017, aes(SITE, SIZE)) +
  geom_boxplot(width = 0.6) +
  geom_jitter(width = 0.15, alpha = 0.2, aes(color = SITE)) +
  theme_pubr() +
  labs(x = "Site",
       y = "Carapace Length (mm)")

lob_a_2017_box

sum_2017 <- lob_a_2017 %>% 
  group_by(SITE) %>% 
  summarize(
    lob_mean = round(mean(SIZE), 2),
    lob_sd = round(sd(SIZE), 2),
    lob_count = length(SIZE),
    lob_var = round(var(SIZE), 2)
    ) %>% 
  mutate(lob_size = paste(as.character(lob_mean), " ± ", as.character(lob_sd)),
         label_text = c("a, b", "a", "a", "a", "b"))

#Output table we will use in the report
tbl_2017 <- sum_2017 %>% 
  select(SITE, lob_size, lob_count) %>% 
  kable(col.names = c("Site  \n\n","Size  \n$(mm)$", "Sample  \nSize"), #Assigning column names
        align = "c") %>% 
  kable_styling(bootstrap_options = c("hover", "condensed"), 
                full_width = FALSE, 
                position = "left") %>% 
  column_spec(1, bold = T, background = "cornsilk") %>% 
  row_spec(0, background = "cornsilk")

tbl_2017

lob_a_2017_column <- ggplot(sum_2017, aes(x = SITE, y = lob_mean)) +
  geom_col(color = "black", fill = "gray", width = 0.7) +
  geom_errorbar(aes(ymin = lob_mean - lob_sd, ymax = lob_mean + lob_sd), width = 0.3) +
  theme_pubr() +
  labs(x = "Site",
       y = "Carapace Length (mm)") +
  expand_limits(y = c(0, 120)) +
  scale_y_continuous(expand = c(0, 0)) +
  geom_text(data = sum_2017, aes(x = SITE, label = label_text), y = 100, size = 8)

lob_a_2017_column

```

```{r, include = FALSE}

#Data exploration

histos <- ggplot(lob_a_2017, aes(SIZE)) +
  geom_histogram(bins = 20) +
  facet_wrap(~SITE, scale = "free")

histos

qqs <- ggplot(lob_a_2017, aes(sample = SIZE)) +
  geom_qq() +
  facet_wrap(~SITE, scale = "free")

qqs

#Normal distribution

```

```{r, include = FALSE}

#One-way ANOVA test
#Post-hoc test

lob_2017_levene <- leveneTest(SIZE ~ SITE, data = lob_a_2017)

lob_2017_levene
#levene's test rejects equal variances

#mean within 4 x's so equal variance (Allison)

#But we can assume equal variance with the four time standard


lob_2017_aov <- aov.test(SIZE ~ SITE, data = lob_a_2017)
lob_2017_aov
#One-way ANOVA tells us that there's a significant differences in samples

lob_2017_ph <- paircomp(lob_2017_aov, adjust.method = "bonferroni")
lob_2017_ph
#post-hoc test shows which one is different

eff_NAPL_CARP <- lob_a_2017 %>% 
  filter(SITE == "NAPL" | SITE == "CARP") %>% 
  cohen.d(SIZE ~ SITE, data=.)

eff_NAPL_CARP

eff_NAPL_IVEE <- lob_a_2017 %>% 
  filter(SITE == "NAPL" | SITE == "IVEE") %>% 
  cohen.d(SIZE ~ SITE, data=.)

eff_NAPL_IVEE

eff_NAPL_MOHK <- lob_a_2017 %>% 
  filter(SITE == "NAPL" | SITE == "MOHK") %>% 
  cohen.d(SIZE ~ SITE, data=.)

eff_NAPL_MOHK
#All three effsize are small

```

### 3. Changes in Lobster Size at MPA and non-MPA Sites
```{r, message = FALSE, echo = FALSE}



```

### 4. Proportions of “legal” lobsters at the 5 sites in 2017

```{r, include = FALSE}

#Chi-square test

lob_count_2017 <- lob_a_2017 %>% 
  mutate (legal = case_when(
    SIZE >= 82.6 ~ "Yes",
    SIZE < 82.6 ~ "No"
  )) %>% 
  count(SITE, legal) %>% 
  spread(legal, n) %>% 
  select(-SITE)

rownames(lob_count_2017) <- c("AQUE", "CARP", "IVEE", "MOHK", "NAPL")

lob_prop_2017 <- prop.table(as.matrix(lob_count_2017), 1)

lob_x2 <- chisq.test(lob_count_2017)

lob_x2

```

```{r, echo = FALSE}

prop_tbl_df <- as.data.frame(lob_count_2017) %>% 
  mutate (Site = c("AQUE", "CARP", "IVEE", "MOHK", "NAPL"),
          Yes_percentage = round(Yes/(Yes + No), 2),
          No_percentage = round(No/(Yes + No), 2),
          MPA = c("Non-MPA", "Non-MPA", "MPA", "Non-MPA", "MPA"),
          Legal = paste(as.character(Yes), "(", as.character(Yes_percentage), ")"),
          Not_legal = paste(as.character(No), "(", as.character(No_percentage), ")")) %>% 
  select(Site, MPA, Legal, Not_legal) %>% 
  kable(col.name = c("Site", "MPA", "Legal Count", "Non-legal Count"),
        align = "c") %>% 
  kable_styling(bootstrap_options = c("hover", "condensed"), 
                full_width = FALSE, 
                position = "left") %>% 
  column_spec(1, bold = T, background = "cornsilk") %>% 
  row_spec(0, background = "cornsilk")

prop_tbl_df

```

